### ISSUE TITLE
Add info about visa and relocation costs to FAQ

### ISSUE THREAD

**Issue by yongrenjie** [alan-turing-institute/REG-handbook#141]
## Summary

As title. These are obviously really useful things for potential applicants to know, and the fact that the Turing sponsors visas is quite a big deal for non-UK nationals :)

Supersedes https://github.com/alan-turing-institute/Hut23/issues/1667

### Todo @yongrenjie 

- [ ] write about visa
- [ ] find someone to write about relocation costs
- [ ] write about equipment (laptop, monitor, etc)

**Comment by penelopeysm** [comment]
Related to #154, but it's probably a good idea to have a separate page on this too. Will work on it
